[Service]
Host = "device-goface"
Port = 49990
ConnectRetries = 20
Labels = []
OpenMsg = "device goface started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

# enable the logging and define the level
[Logging]
EnableRemote = true
File = ".edgex/logs/device-goface.log"

# Pre-define Devices - use Name for API calls
[[DeviceList]]
  Name = "Device-Goface-01"
  Profile = "device-goface"
  Description = "Goface Recognizer Device"
  Labels = [ "goface" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.Other]
      Address = "goface01"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "10s"
    OnChange = false
    Resource = "Switch"    
  [[DeviceList.AutoEvents]]
    OnChange = false
    Frequency = "1s"
    Resource = "goface"
