[Writable]
LogLevel = 'INFO'
    [Writable.StoreAndForward]
    Enabled = false
    RetryInterval = 50000 # 5mins
    MaxRetryCount = 10

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is a sample Filter/XML/Post Transform Application Service'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Database]
Type = "mongodb"
Host = "localhost"
Port = 27017
Timeout = 5000
Username = ""
Password = ""

[Logging]
EnableRemote = false
File = './logs/simple-filter-xml-post.log'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Logging]
  Protocol = "http"
  Host = "localhost"
  Port = 48061

  # Required when using Store and Forward
  [Clients.Scheduler]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48085

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5563
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

# Choose either an HTTP trigger or MessageBus trigger (aka Binding)

#[Binding]
#Type="http"

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic="somewhere"



